### PR TITLE
Separate gitignores

### PR DESCRIPTION
**Pull request by neon-glowstick**
There are two projects in the repo and I think it makes sense to have a separate gitignore for each of them. I kept the gitignore at the root to exclude the server build output. Files are from https://github.com/github/gitignore/blob/main/Unity.gitignore and https://github.com/github/gitignore/blob/main/community/DotNet/core.gitignore. 

Branched from New-Server-Ready because that is where #81 was merged.

I've dropped the ignored files in a [separate branch](https://github.com/neon-glowstick/Basis/pull/1) and it seems to work fine on a clean clone.

### CODE REVIEW

**Comment by dooly123** [comment]
just looking over it now, did not even know that git supported multiple git ignores, things you learn  ;)

**Comment by dooly123** [comment]
Had a chat with one or two other people about this, they both don't want it being 2 separate files. (guess it comes down to preference) will run it by the other contributes and see what they think

**Comment by neon-glowstick** [comment]
The argument for multiple files is that you have two separate codebases the same git repo. If you decide to move a project its easier if the gitignore follows along with it. And the projects may have conflicting requirements, such as Basis (the unity project) which should not include .csproj files, but Basis Server (a dotnet project) must include them.

**Comment by yewnyx** [comment]
Strong agree that separate gitignores are preferable for multi project repositories

**Comment by dooly123** [comment]
sounds like we will go ahead and do it then :)

**Comment by dooly123** [comment]
tested all looks good, thanks!

**Pull request merged**
